In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Info)=
# Info

*Displaying summary information about a molecular system and its elements.*

MolSysMT provides a function to display a concise summary of a molecular system and its elements: {func}`molsysmt.basic.info`. This function works at different levels depending on the selected element type — `atom`, `group`, `component`, `molecule`, `chain`, `entity`, or `system`. The default output is a Pandas `Styler`; use `output_type='dataframe'` for a DataFrame or `'dictionary'` for row records.

:::{hint}
:class: dropdown

Visit the section {ref}`Introduction_Elements` for a detailed overview of element hierarchy in MolSysMT.
:::

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.basic.info`.
:::

The native convenience method `molsys.info(...)` uses the same validated
summary boundary by default. Element aliases and scalar selections are
normalized, and invalid options fail. It requires a topology and returns a
Styler; use `msm.info(...)` for another representation or structure selection.
Keep `skip_digestion=False` for ordinary public calls.

## Basic usage

Let's show how this function works using a PDB structure (`181L`):

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('181L')

By default, {func}`molsysmt.basic.info` supplies a styled summary table of the system:

In [4]:
msm.info(molsys)

:::{tip}
:class: dropdown

All methods defined in the {ref}`molsysmt.basic <API basic>` module can also be invoked from the main level of the library. Hence, {func}`molsysmt.info` is the same function as {func}`molsysmt.basic.info`.
:::

But summary information on other elements such as atoms, groups, components, molecules, chains or entities can be obtained.

## With atoms

Example of how the function works at the `atom` level:

In [5]:
msm.info(molsys, element='atom', selection='molecule_type=="ion"')

## With groups

Example of how the function works at the `group` level:

In [6]:
msm.info(molsys, element='group', selection=[9,10,11,12])

## With components

The function can also be applied to the component level, as shown below:

In [7]:
msm.info(molsys, element='component', selection='molecule_type=="small molecule"')

## With molecules

Let's see an example of how this function works with molecules:

In [8]:
msm.info(molsys, element='molecule',
         selection='molecule_type!=["water", "protein"] within 4.0 angstroms of molecule_type=="protein"')

## With chains

The function can also be applied to `chain` elements as shown below:

In [9]:
msm.info(molsys, element='chain', selection='molecule_type=="water"')

## With entities

This example shows how to obtain a summary of `entity` elements:

In [10]:
msm.info(molsys, element='entity')

## With system

Let's see an example of how this function works with the system (default option):

In [11]:
msm.info(molsys)

## Restricting a summary to a scope

Use `mask` to intersect `selection` with an explicit scope. Integer indices and
Boolean flags use the same element level as the table: a group summary needs a
group mask. No atom-to-group conversion is implicit. A system summary uses an
atom scope, like its existing selection argument; structure selection remains
independent. An active mask returns the sorted, unique intersection, including
an empty table when no members match. None or `'all'` preserves the unmasked path.
The native `molsys.info(...)` shortcut accepts the same mask.

In [12]:
import molsysmt as msm
molsys = msm.convert(msm.systems['T4 lysozyme L99A']['181l.pdb'],
                     to_form='molsysmt.MolSys')
table = msm.info(molsys, element='atom', selection=[3, 1, 2],
                 mask=[2, 3], output_type='dataframe')
assert table['index'].tolist() == [2, 3]
print(table['index'].tolist())
group_table = molsys.info(element='group', selection=[0, 1, 2], mask=[1])
assert group_table.data['index'].tolist() == [1]
print(group_table.data['index'].tolist())

[2, 3]
[1]

## Inspecting native objects briefly

`repr(molsys)` and the notebook's plain object display summarize stored metadata
without formatting coordinates, traversing graphs, validating the system or
reading file contents. Native containers, dictionary wrappers and file handlers
use this bounded summary; ordinary Python dictionaries keep their normal repr.
Use `msm.info(..., output_type='dataframe')` or native properties for structured
queries. The text is a human summary, not a serialization or parsing contract.

Counts of zero and `None` are distinct: zero denotes an explicit empty axis or
collection, while `None` denotes an undeclared axis/domain or an unresolved
reference count. A structure container with no atom-aligned series has no known
atom axis. Bond counts belong to ChemicalStates and use its selected state; an
ambiguous reference is not silently selected. Pure Topology has no chemical counts. Named analyses are counted without
printing their names or data. Sparse result views report selected occurrences
and evaluated structures, while `n_stored_relations` refers to their backing table.
File handlers report their cached format/status without loading structures.
No quantities are converted or printed by these summaries.

In [13]:
import numpy as np
import molsysmt as msm
from molsysmt.native import MolSys, Structures
molsys = MolSys(n_atoms=3)
molsys.structures = Structures(
    coordinates=msm.pyunitwizard.quantity(np.zeros((2, 3, 3)), 'nm'))
text = repr(molsys)
assert 'n_atoms=3' in text and 'n_structures=2' in text
assert 'topology=True' in text
assert len(text) < 300
print(molsys)
print(molsys.structures)

MolSys(n_atoms=3, n_structures=2, topology=True, structures=True, n_chemical_states=1, n_interaction_analyses=0, molecular_mechanics=True)
Structures(n_atoms=3, n_structures=2, coordinates=True, box=False)

## Querying native domains

You can use `get()` and `info()` on `MolSys`, `Topology`, `Structures`,
`ChemicalStates`, `Interactions` and `MolSysBuilder`. They share the basic-tool
attribute vocabulary, validation and result conventions. `get()` returns a value,
an ordered list of values or an attribute dictionary; `info()` offers a Styler,
a DataFrame or dictionary records. Each object exposes its available domain;
missing attributes retain the basic-tool behavior.

Use named arguments when moving between the free functions and instance methods.
`MolSys`'s existing positional arguments are preserved: native `get()` accepts
`chemical_state` by keyword, and native `info()` accepts `structure_indices`,
`output_type` and `mask` by keyword. For an instance call, omit the free
function's `molecular_system` argument. Leave `skip_digestion=False` for user input.

Explicit index queries use known native providers. Expressions and nested
selections retain the existing selector. Structures quantities follow the
session unit policy and selected axes preserve order and repetitions. Existing
`get_coordinates()`, `get_box()` and `get_time()` remain available. Interaction
occurrences continue to use `query()`, `between_selections()` and `to_page()`;
the shared molecular `get()` does not replace that sparse-query API.

Dictionary forms and file handlers keep the form-agnostic `msm.get()`/`msm.info()`
route. A plain Python dictionary's `.get()` keeps its ordinary Python meaning.

See the {ref}`native query API <API Native Queries>` for the actual method signatures.

In [14]:
import numpy as np
import molsysmt as msm
from molsysmt.native import MolSys, Structures, MolSysBuilder
molsys = MolSys(n_atoms=3)
molsys.structures = Structures(
    coordinates=msm.pyunitwizard.quantity(np.arange(18).reshape(2, 3, 3), 'nm'))
assert molsys.get(n_atoms=True) == 3
assert molsys.topology.get(element='atom', selection=[2, 0], atom_index=True) == [2, 0]
selected = molsys.structures.get(element='atom', selection=[2, 0],
    structure_indices=[1, 0, 1], coordinates=True)
assert selected.shape == (3, 2, 3)
np.testing.assert_array_equal(msm.pyunitwizard.get_value(selected, to_unit='nm')[0],
                             [[15, 16, 17], [9, 10, 11]])
assert molsys.chemical_states.get(n_chemical_states=True) == 1
assert MolSysBuilder(molsys).get(n_atoms=True) == 3
summary = molsys.structures.info(output_type='dictionary')
assert summary[0]['n_atoms'] == 3 and summary[0]['n_structures'] == 2
print(molsys.get(n_atoms=True, n_structures=True, output_type='dictionary'))
print(selected.shape)

{'n_atoms': 3, 'n_structures': 2}
(3, 2, 3)

:::{seealso}
:class: dropdown

**Related Tools & References**

- {ref}`Introduction_Elements`: Describe the different hierarchical levels (atom, group, component, molecule, chain, entity, system) used in molecular systems.
- {ref}`Tutorial_Convert`: Convert a molecular system into another form or forms with {func}`molsysmt.basic.convert`.
- {ref}`Tutorial_Info`: Display summary information about a molecular system and its elements with {func}`molsysmt.basic.info`.
- {ref}`Tutorial_Get_label`: Generate formatted labels for elements in a molecular system with {func}`molsysmt.basic.get_label`.
:::